
import { 
  Database,
  Package,
  Smartphone,
  Settings,
  Users,
  BarChart,
  Shield,
  FileText,
  Globe,
  Building2,
  Calendar,
  MessageSquare
} from "lucide-react";

export const applications = [
  {
    id: 1,
    name: "Online Report Tools",
    description: "ERP Report Tools - Công cụ báo cáo trực tuyến",
    icon: Database,
    category: "all",
    departments: ["production", "hr", "purchase"],
    type: "desktop",
    url: "Online-Report-Tool://Hello-app",
    status: "online",
    users: 1250,
    rating: 4.8,
    version: "v1.3.5",
    lastUpdated: "2025-03-15",
    isNew: false,
    isFavorite: true,
    badge: "success"
  },
  {
    id: 2,
    name: "Purchase Application",
    description: "Purchasing application - Ứng dụng quản lý mua hàng",
    icon: Package,
    category: "purchase",
    departments: ["purchase"],
    type: "desktop",
    url: "Purchasing-Management-Tool://Hello-app",
    status: "online",
    users: 450,
    rating: 4.9,
    version: "v2.1.0",
    lastUpdated: "2025-04-01",
    isNew: true,
    isFavorite: false,
    badge: "warning"
  },
  {
    id: 3,
    name: "Scan Out Location",
    description: "Scan in and out - Quét vào ra vị trí",
    icon: Smartphone,
    category: "production", 
    departments: ["production"],
    type: "desktop",
    url: "Scan-Out-Location://Hello-app",
    status: "online",
    users: 85,
    rating: 4.7,
    version: "v2.1.0",
    lastUpdated: "2025-04-01",
    isNew: true,
    isFavorite: false,
    badge: "warning"
  },
  {
    id: 4,
    name: "Pakship",
    description: "Shipping scanner - Máy quét vận chuyển",
    icon: Settings,
    category: "inventory",
    departments: ["inventory"],
    type: "desktop",
    url: "Pakship-Tool://Hello-app",
    status: "online",
    users: 320,
    rating: 4.6,
    version: "v3.2.1",
    lastUpdated: "2025-04-10",
    isNew: false,
    isFavorite: true,
    badge: "success"
  },
  {
    id: 5,
    name: "HR Portal",
    description: "Cổng thông tin nhân sự và chấm công",
    icon: Users,
    category: "hr",
    departments: ["hr"],
    type: "web",
    url: "https://hr.company.local",
    status: "maintenance",
    users: 890,
    rating: 4.5,
    version: "v1.8.2",
    lastUpdated: "2025-03-20",
    isNew: false,
    isFavorite: false,
    badge: "info"
  },
  {
    id: 6,
    name: "Quality Control Mobile",
    description: "Ứng dụng kiểm tra chất lượng di động",
    icon: BarChart,
    category: "quality",
    departments: ["quality"],
    type: "mobile",
    downloadUrl: "/downloads/qc-mobile.apk",
    status: "online",
    users: 156,
    rating: 4.4,
    version: "v1.5.3",
    lastUpdated: "2025-04-05",
    isNew: false,
    isFavorite: true,
    badge: "success"
  },
  {
    id: 7,
    name: "Security Dashboard",
    description: "Giám sát bảo mật và cảnh báo hệ thống",
    icon: Shield,
    category: "it",
    departments: ["it"],
    type: "web",
    url: "https://security.company.local",
    status: "online",
    users: 25,
    rating: 4.9,
    version: "v2.0.1",
    lastUpdated: "2025-04-12",
    isNew: false,
    isFavorite: true,
    badge: "success"
  },
  {
    id: 8,
    name: "Document Center",
    description: "Trung tâm quản lý tài liệu số",
    icon: FileText,
    category: "all",
    departments: ["all"],
    type: "web",
    url: "https://docs.company.local",
    status: "online",
    users: 678,
    rating: 4.3,
    version: "v1.2.0",
    lastUpdated: "2025-03-25",
    isNew: false,
    isFavorite: false,
    badge: "info"
  }
];

export const companyWebPages = [
  {
    id: 'web1',
    name: "Company Portal",
    description: "Cổng thông tin chính của công ty",
    icon: Globe,
    url: "https://portal.company.com",
    category: "General",
    isInternal: true,
    users: 890,
    rating: 4.7,
    version: "v2.0.1",
    lastUpdated: "2025-04-15",
    status: "online",
    badge: "success"
  },
  {
    id: 'web2', 
    name: "Employee Self Service",
    description: "Dịch vụ tự phục vụ nhân viên",
    icon: Users,
    url: "https://ess.company.com",
    category: "HR",
    isInternal: true,
    users: 456,
    rating: 4.6,
    version: "v1.8.3",
    lastUpdated: "2025-04-10",
    status: "online",
    badge: "success"
  },
  {
    id: 'web3',
    name: "Company Website",
    description: "Website chính thức của công ty",
    icon: Building2,
    url: "https://www.company.com",
    category: "Public",
    isInternal: false,
    users: 2340,
    rating: 4.8,
    version: "v3.1.0",
    lastUpdated: "2025-04-12",
    status: "online",
    badge: "success"
  },
  {
    id: 'web4',
    name: "Learning Management",
    description: "Hệ thống quản lý đào tạo",
    icon: Calendar,
    url: "https://learning.company.com",
    category: "Training",
    isInternal: true,
    users: 234,
    rating: 4.4,
    version: "v1.5.2",
    lastUpdated: "2025-04-08",
    status: "online",
    badge: "info"
  },
  {
    id: 'web5',
    name: "Internal Communication",
    description: "Hệ thống giao tiếp nội bộ",
    icon: MessageSquare,
    url: "https://comm.company.com",
    category: "Communication",
    isInternal: true,
    users: 567,
    rating: 4.5,
    version: "v2.2.1",
    lastUpdated: "2025-04-05",
    status: "maintenance",
    badge: "warning"
  }
];
