import { UploadHistory, MasterDataPreview } from "@/types/masterData";

export const mockUploadHistory: UploadHistory[] = [
  {
    id: "1",
    filename: "training_master_data_2024_Q1.xlsx",
    size: 2456789,
    uploadDate: new Date("2024-03-15T10:30:00"),
    modifiedDate: new Date("2024-03-15T10:30:00"),
    status: "processed",
    rowCount: 1250,
  },
  {
    id: "2",
    filename: "course_data_jan_2024.xlsx",
    size: 1234567,
    uploadDate: new Date("2024-02-20T14:20:00"),
    modifiedDate: new Date("2024-02-20T14:20:00"),
    status: "processed",
    rowCount: 850,
  },
  {
    id: "3",
    filename: "ng_training_december.xlsx",
    size: 3567890,
    uploadDate: new Date("2023-12-28T09:15:00"),
    modifiedDate: new Date("2023-12-28T09:15:00"),
    status: "processed",
    rowCount: 1580,
  },
  {
    id: "4",
    filename: "rpd_course_data_2023.xlsx",
    size: 987654,
    uploadDate: new Date("2023-11-10T16:45:00"),
    modifiedDate: new Date("2023-11-10T16:45:00"),
    status: "processed",
    rowCount: 420,
  },
  {
    id: "5",
    filename: "master_data_processing.xlsx",
    size: 2100000,
    uploadDate: new Date("2024-03-16T11:00:00"),
    modifiedDate: new Date("2024-03-16T11:00:00"),
    status: "pending",
    rowCount: undefined,
  },
];

export const mockPreviewData: MasterDataPreview = {
  fileId: "1",
  filename: "training_master_data_2024_Q1.xlsx",
  totalRows: 1250,
  processedAt: new Date(),
  courses: [
    {
      courseCode: "NG-001",
      courseName: "New Graduate Training Program - Basic",
      startDate: "2024-03-01",
      endDate: "2024-05-30",
    },
    {
      courseCode: "NG-002",
      courseName: "New Graduate Training Program - Advanced",
      startDate: "2024-06-01",
      endDate: "2024-08-30",
    },
    {
      courseCode: "RPD-102",
      courseName: "Removable Partial Denture Advanced",
      startDate: "2024-03-15",
      endDate: "2024-04-15",
    },
    {
      courseCode: "FPD-201",
      courseName: "Fixed Partial Denture Mastery",
      startDate: "2024-04-01",
      endDate: "2024-06-30",
    },
    {
      courseCode: "IMPL-301",
      courseName: "Implant Dentistry Foundation",
      startDate: "2024-05-01",
      endDate: "2024-07-31",
    },
  ],
  diaries: [
    {
      diaryCode: "D-2024-001",
      participantName: "Nguyen Van A",
      courseCode: "NG-001",
      attendanceDate: "2024-03-05",
      status: "Present",
      notes: "Good progress on basic techniques",
      location: "Room 101",
      instructor: "Dr. Tran Van Minh",
      duration: 120,
      score: 85,
    },
    {
      diaryCode: "D-2024-002",
      participantName: "Le Thi B",
      courseCode: "RPD-102",
      attendanceDate: "2024-03-16",
      status: "Present",
      notes: "Excellent performance on partial denture design",
      location: "Lab 2",
      instructor: "Dr. Pham Thi Hong",
      duration: 180,
      score: 92,
    },
    {
      diaryCode: "D-2024-003",
      participantName: "Tran Van C",
      courseCode: "NG-001",
      attendanceDate: "2024-03-06",
      status: "Present",
      notes: "Needs improvement on casting procedures",
      location: "Room 101",
      instructor: "Dr. Tran Van Minh",
      duration: 120,
      score: 78,
    },
    {
      diaryCode: "D-2024-004",
      participantName: "Pham Thi D",
      courseCode: "FPD-201",
      attendanceDate: "2024-04-02",
      status: "Present",
      notes: "Outstanding work on crown preparation",
      location: "Lab 3",
      instructor: "Dr. Nguyen Van Hai",
      duration: 150,
      score: 95,
    },
    {
      diaryCode: "D-2024-005",
      participantName: "Hoang Van E",
      courseCode: "IMPL-301",
      attendanceDate: "2024-05-03",
      status: "Absent",
      notes: "Medical leave",
      location: "Lab 4",
      instructor: "Dr. Le Thi Lan",
      duration: 0,
      score: 0,
    },
    {
      diaryCode: "D-2024-006",
      participantName: "Vo Thi F",
      courseCode: "NG-002",
      attendanceDate: "2024-06-05",
      status: "Present",
      notes: "Strong understanding of advanced concepts",
      location: "Room 102",
      instructor: "Dr. Tran Van Minh",
      duration: 150,
      score: 88,
    },
    {
      diaryCode: "D-2024-007",
      participantName: "Dang Van G",
      courseCode: "RPD-102",
      attendanceDate: "2024-03-18",
      status: "Present",
      notes: "Good progress, improving steadily",
      location: "Lab 2",
      instructor: "Dr. Pham Thi Hong",
      duration: 180,
      score: 82,
    },
  ],
  examResults: [
    {
      diaryCode: "D-2024-001",
      participantName: "Nguyen Van A",
      test1Name: "Theory Test - Basic Concepts",
      test1Score: 85,
      test1Evaluation: "Good",
      test2Name: "Practical Test - Casting",
      test2Score: 88,
      test2Evaluation: "Very Good",
      test3Name: "Final Assessment - Complete Denture",
      test3Score: 90,
      test3Evaluation: "Excellent",
    },
    {
      diaryCode: "D-2024-002",
      participantName: "Le Thi B",
      test1Name: "Theory Test - RPD Design",
      test1Score: 92,
      test1Evaluation: "Excellent",
      test2Name: "Practical Test - Framework",
      test2Score: 95,
      test2Evaluation: "Excellent",
      test3Name: "Final Assessment - Complete RPD",
      test3Score: 94,
      test3Evaluation: "Excellent",
    },
    {
      diaryCode: "D-2024-003",
      participantName: "Tran Van C",
      test1Name: "Theory Test - Basic Concepts",
      test1Score: 78,
      test1Evaluation: "Satisfactory",
      test2Name: "Practical Test - Casting",
      test2Score: 75,
      test2Evaluation: "Satisfactory",
      test3Name: "Final Assessment - Complete Denture",
      test3Score: 80,
      test3Evaluation: "Good",
    },
    {
      diaryCode: "D-2024-004",
      participantName: "Pham Thi D",
      test1Name: "Theory Test - FPD Principles",
      test1Score: 95,
      test1Evaluation: "Excellent",
      test2Name: "Practical Test - Crown Prep",
      test2Score: 96,
      test2Evaluation: "Excellent",
      test3Name: "Final Assessment - Bridge Work",
      test3Score: 97,
      test3Evaluation: "Outstanding",
    },
    {
      diaryCode: "D-2024-006",
      participantName: "Vo Thi F",
      test1Name: "Theory Test - Advanced Concepts",
      test1Score: 88,
      test1Evaluation: "Very Good",
      test2Name: "Practical Test - Complex Cases",
      test2Score: 87,
      test2Evaluation: "Very Good",
      test3Name: "Final Assessment - Comprehensive",
      test3Score: 89,
      test3Evaluation: "Very Good",
    },
  ],
};
